(function (globalScope, factory) {
  if (typeof module === "object" && module.exports) {
    module.exports = factory();
    return;
  }

  globalScope.AdmitCardWorkflowRuntime = factory();
})(typeof globalThis !== "undefined" ? globalThis : this, () => {
  function createWorkflowRuntimeController({
    BATCH_PRINT_JOB_TIMEOUT_MS,
    BATCH_PRINT_STATUS_POLL_INTERVAL_MS,
    MIN_UPLOAD_OVERLAY_DISPLAY_MS,
    apiRequest,
    apiRequestForBlobWithProgress,
    apiRequestWithUploadProgress,
    arrayBufferToBase64,
    buildApiUrl,
    buildUploadSummaryMessage,
    clearSelectedUploadFiles,
    closeModal,
    createAdmitCardWorkflowController,
    createBusyOverlayController,
    createExamineeUploadWorkflowController,
    createPdfGenerationState,
    createUploadState,
    getBatchPrintDownloadElements,
    getDocumentBody,
    getExamineeGridRows,
    getGridRowId,
    getGridRows,
    getGridSelectedRowIds,
    getPdfGenerationElements,
    getUploadFileInput,
    getUploadOverlayElements,
    getUploadPreviewMount,
    getUploadPhotoArchiveInput,
    handleAuthenticationFailure,
    hideToast,
    loadBootstrapData,
    mergeUploadResult,
    readFileAsArrayBuffer,
    renderView,
    setUploadOverlayStateFallback,
    showToast,
    state,
    wait,
    waitForNextFrame,
  }) {
    const busyOverlayController = createBusyOverlayController({
      createPdfGenerationState,
      createUploadState,
      getDocumentBody,
      getPdfGenerationElements,
      getUploadOverlayElements,
      hideToast,
      minUploadOverlayDisplayMs: MIN_UPLOAD_OVERLAY_DISPLAY_MS,
      showToast,
      state,
      wait,
    });
    const {
      buildBusyOverlayMessage,
      buildPdfGenerationMessage,
      buildUploadOverlayMessage,
      closeUploadOverlayWithAlert,
      closeUploadOverlayWithToast,
      isBusyOverlayActive,
      isPdfGenerationActive,
      isUploadActive,
      normalizeProgressValue,
      resetPdfGenerationState,
      resetUploadState,
      runWithPdfGenerationLock,
      setPdfGenerationState,
      setUploadOverlayState,
      showUploadFailureAlert,
      syncAppBusyState,
      syncPdfGenerationOverlay,
      syncUploadOverlay,
    } = busyOverlayController;

    const examineeUploadWorkflowController = createExamineeUploadWorkflowController({
      apiRequest,
      apiRequestWithUploadProgress,
      arrayBufferToBase64,
      buildUploadSummaryMessage,
      clearSelectedUploadFiles,
      closeUploadOverlayWithAlert,
      closeUploadOverlayWithToast,
      getUploadFileInput,
      getUploadPreviewMount,
      getUploadPhotoArchiveInput,
      isUploadActive,
      loadBootstrapData,
      mergeUploadResult,
      readFileAsArrayBuffer,
      setUploadOverlayState: typeof setUploadOverlayState === "function" ? setUploadOverlayState : setUploadOverlayStateFallback,
      showUploadFailureAlert,
      state,
      waitForNextFrame,
    });
    const {
      clearExamineeUploadPreview,
      previewSelectedExamineePhotoArchiveFile,
      previewSelectedExamineeImportFile,
      readUploadFileAsBase64,
      setExamineeUploadMode,
      uploadPhotoArchiveFile,
      uploadSelectedExamineeFile,
      updateExamineeImportExistingDataPolicy,
    } = examineeUploadWorkflowController;

    const admitCardWorkflowController = createAdmitCardWorkflowController({
      BATCH_PRINT_JOB_TIMEOUT_MS,
      BATCH_PRINT_STATUS_POLL_INTERVAL_MS,
      apiRequest,
      apiRequestForBlobWithProgress,
      buildApiUrl,
      closeModal,
      getBatchPrintDownloadElements,
      getExamineeGridRows,
      getGridRowId,
      getGridRows,
      getGridSelectedRowIds,
      handleAuthenticationFailure,
      loadBootstrapData,
      normalizeProgressValue,
      renderView,
      runWithPdfGenerationLock,
      setPdfGenerationState,
      showToast,
      state,
      wait,
    });
    const {
      batchPrintSelectedExaminees,
      cancelBatchPrintJob,
      fetchExamineeAdmitCardPdfUrl,
      getSelectedAdmitCardExamineeCount,
      getSelectedAdmitCardExaminees,
      normalizeExamineeNoList,
      openPdfWindow,
      prepareBatchPrintDownloadModal,
      printExamineeAdmitCard,
      printPdfUrl,
      recordExamineePrint,
      submitBatchPrintDownloadSelection,
      updateBatchPrintOutputMode,
    } = admitCardWorkflowController;

    return Object.freeze({
      batchPrintSelectedExaminees,
      buildBusyOverlayMessage,
      buildPdfGenerationMessage,
      buildUploadOverlayMessage,
      closeUploadOverlayWithAlert,
      closeUploadOverlayWithToast,
      fetchExamineeAdmitCardPdfUrl,
      getSelectedAdmitCardExamineeCount,
      getSelectedAdmitCardExaminees,
      isBusyOverlayActive,
      isPdfGenerationActive,
      isUploadActive,
      normalizeExamineeNoList,
      normalizeProgressValue,
      openPdfWindow,
      cancelBatchPrintJob,
      clearExamineeUploadPreview,
      previewSelectedExamineePhotoArchiveFile,
      prepareBatchPrintDownloadModal,
      previewSelectedExamineeImportFile,
      printExamineeAdmitCard,
      printPdfUrl,
      readUploadFileAsBase64,
      recordExamineePrint,
      resetPdfGenerationState,
      resetUploadState,
      runWithPdfGenerationLock,
      setExamineeUploadMode,
      setPdfGenerationState,
      setUploadOverlayState,
      showUploadFailureAlert,
      submitBatchPrintDownloadSelection,
      syncAppBusyState,
      syncPdfGenerationOverlay,
      syncUploadOverlay,
      updateBatchPrintOutputMode,
      updateExamineeImportExistingDataPolicy,
      uploadPhotoArchiveFile,
      uploadSelectedExamineeFile,
    });
  }

  return Object.freeze({
    createWorkflowRuntimeController,
  });
});
